version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity | jq ".Account" -r)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/stress
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com"
      - docker build -t $REPOSITORY_URI:latest .
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Building the Docker image...
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/stress
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com"
      - docker build -t $REPOSITORY_URI:latest .
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

artifacts:
  files: 
    - imageDetail.json
