apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ap-unicorn-cluster
  region: ap-notheast-2
  version: '1.26'

privateCluster:
  enabled: true
  additionalEndpointServices:
    - autoscaling
    - logs

vpc:
  id: vpc-0f01b30c1a1cdaac3
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-0f516155e6856e88d
      ap-northeast-2b:
        id: subnet-0479af4eaadc4534d
      ap-northeast-2c:
        id: subnet-0d05800509573228b

managedNodeGroups:
  - name: ap-unicorn-nodegroup-tools
    minSize: 2
    desiredCapacity: 2
    maxSize: 16
    labels:
      unicorn/dedicated: tool
    instanceType: c6g.large
    amiFamily: Bottlerocket
    privateNetworking: true
    taints:
      - key: dedicated
        value: tool
        effect: NoSchedule
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: ap-unicorn-nodegroup-apps
    labels:
      unicorn/dedicated: apps
    instanceType: c6g.xlarge
    taints:
      - key: dedicated
        value: app
        effect: NoSchedule
    desiredCapacity: 2
    minSize: 2
    maxSize: 16
    privateNetworking: true
    amiFamily: Bottlerocket
    iam:
      withAddonPolicies:
        autoScaler: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
