apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ap-unicorn-cluster
  region: ap-northeast-2
  version: '1.26'

privateCluster:
  enabled: true
  additionalEndpointServices:
    - autoscaling
    - logs

vpc:
  id: vpc-0bd4486f0cac8acc5
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-09e9cdec9d1b187c4
      ap-northeast-2b:
        id: subnet-08d103d5b5cd9fa46
      ap-northeast-2c:
        id: subnet-04c65fbc5b206f323

managedNodeGroups:
  - name: ap-unicorn-nodegroup-tools
    minSize: 2
    desiredCapacity: 2
    maxSize: 16
    labels:
      unicorn/dedicated: tool
    instanceType: c6g.large
    amiFamily: Bottlerocket
    privateNetworking: true
    taints:
      - key: dedicated
        value: tool
        effect: NoSchedule
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: ap-unicorn-nodegroup-apps
    labels:
      unicorn/dedicated: apps
    instanceType: c6g.xlarge
    taints:
      - key: dedicated
        value: app
        effect: NoSchedule
    desiredCapacity: 2
    minSize: 2
    maxSize: 16
    privateNetworking: true
    amiFamily: Bottlerocket
    iam:
      withAddonPolicies:
        autoScaler: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
