apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: token
  namespace: dev
spec:
  podSelector: 
    matchLabels:
      app: token
  securityGroups:
    groupIds:
      - sg-09a10cce206274d70
      - sg-09ff7f198e954a459
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: token
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: token
  template:
    metadata:
      labels:
        app: token
    spec:
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: app
      containers:
      - name: webapp
        image: 790946953677.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
        command:
          - ./app
          - -redisEndpoint
          - clustercfg.ap-unicorn-redis-cluster.c6cgsw.apn2.cache.amazonaws.com:6379
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: token
  namespace: dev
spec:
  selector:
    app: token
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: token
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: token
  minReplicas: 2
  maxReplicas: 64
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 40
