apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: us-unicorn-cluster
  region: us-east-1
  version: '1.26'

privateCluster:
  enabled: true
  additionalEndpointServices:
    - autoscaling
    - logs

vpc:
  id: vpc-0d2a0e4edcde6d951
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-0ea8eab27aceb02f9
      ap-northeast-2b:
        id: subnet-0d334fea47c1d46c3
      ap-northeast-2c:
        id: subnet-04f26561c5e6189ba

managedNodeGroups:
  - name: us-unicorn-nodegroup-tools
    minSize: 2
    desiredCapacity: 2
    maxSize: 16
    labels:
      unicorn/dedicated: tool
    instanceType: c6g.large
    amiFamily: Bottlerocket
    privateNetworking: true
    taints:
      - key: dedicated
        value: tool
        effect: NoSchedule
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: us-unicorn-nodegroup-apps
    labels:
      unicorn/dedicated: apps
    instanceType: c6g.xlarge
    taints:
      - key: dedicated
        value: app
        effect: NoSchedule
    desiredCapacity: 2
    minSize: 2
    maxSize: 16
    privateNetworking: true
    amiFamily: Bottlerocket
    iam:
      withAddonPolicies:
        autoScaler: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
