apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./location.yaml
  - ./status.yaml
  - ./stress.yaml
  - ./token.yaml
  - ./unicorn.yaml
  - ./ingress.yaml

namespace: dev
